// angular-frontend/src/app/items/items.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../data.service';
import { Observable } from 'rxjs';
import { ActivatedRoute } from "@angular/router";

@Component({
  selector: 'app-items',
  templateUrl: './items.component.html',
  styleUrls: ['./items.component.scss']
})
export class ItemsComponent implements OnInit {

  collectionId$: Object;
  collection$: Object;
  items$: Object;
  
  constructor(private route: ActivatedRoute, private data: DataService) { 
     this.route.params.subscribe( params => this.collectionId$ = params.collectionId );
  }

  ngOnInit() {
    this.data.getCollection(this.collectionId$).subscribe(
      data => this.collection$ = data
    );
    this.data.getItemsInCollection(this.collectionId$).subscribe(
      data => this.items$ = data
    );

  }

}
<h1>Show Collection</h1>
<div *ngIf="collection$">
  

  <div class="row">
      <div class="col-4">
          <span class="h3">{{collection$.Name}}</span>
      </div>
      <div class="col-4">
          <span class="h3">Collected: {{collection$.Collected}} / {{collection$.Total}}</span>
      </div>
      <div class="col-4">
          <a href="./" class="btn btn-primary float-right ml-2">Back</a>
          <a href="./collections/edit/{{collection$.CollectionId}}" class="btn btn-warning float-right">Edit</a>
      </div>
  </div>

  <span class="h3">Items</span>
  <div class="row">
    <div class="col-12">
        <a href="./collection/{{collectionId$}}/items/new" class="btn btn-primary mt-2 mb-2">New</a>
    </div>
  </div>
  
  <table class="table">
      <tr>
          <th>Name</th>
          <th>Value</th>
          <th>Collected</th>
          <th style="width:70px">Actions</th>
      </tr>
      <tr *ngFor="let item of items$">
        <td>{{item.Name}}</td>  
        <td>${{item.Price.toFixed(2)}}</td>
        <td>
          <div *ngIf="item.Collected; else notCollected">
            Yes
          </div>
          <ng-template #notCollected>
            No
          </ng-template>
        </td>
        <td><a href="./collection/{{collection$.CollectionId}}/items/edit/{{item.ItemId}}" class="btn btn-info" style="color: white">Info</a></td>
      </tr>
  </table>

</div>

// react-frontend/src/items/index.js
import React, { Component } from 'react';
import YesNoFromBoolean from '../components/YesNoFromBoolean';

const API = 'http://localhost:4000/api/items/collection/';

class ItemIndex extends Component {  

  constructor(props){
    super(props) 
    this.state = {
      items: [],
    }
  }
  
  componentDidMount() {

    this.data = fetch(API + this.props.collectionId)
      .then(response => response.json())
      .then(data => this.setState( {items:  data} )  );
      // .then(data => console.log(data));
  }

  render() {
    return (
      <div>
        <a href={`/collections/${this.props.collectionId}/items/new`} className="btn btn-primary mt-2 mb-2" style={{color: 'white'}}>New</a>
        <table className="table">
          <tbody>
          <tr>
            <th>Name</th>
            <th>Value</th>
            <th>Collected</th>
            <th style={{width: 80 + 'px'}}>Actions</th>
          </tr>

          {this.state.items.map(function(item, key) {
               return (
                  <tr key = {key}>
                      <td>{item.Name}</td>
                      <td>${item.Price.toFixed(2)}</td>
                      <td>
                      <YesNoFromBoolean active={item.Collected} />
                      </td>
                      <td style={{width: 80 + 'px'}}>
                        <a href={`/collections/${item.CollectionId}/items/edit/${item.ItemId}`} className="btn btn-info">Info</a>
                      </td>
                  </tr>
                )
          })}
          </tbody>
        </table>
      </div>
    );
  }


}

export default ItemIndex;
