// react-frontend/src/collections/index.js
import React, { Component } from 'react';

const API = 'http://localhost:4000/api/collections';

class CollectionIndex extends Component {

 

  constructor(props){
    super(props) 
    this.state = {
      collections: [],
    }
  }

  componentDidMount() {
    this.data = fetch(API)
      .then(response => response.json())
      .then(data => this.setState( {collections:  data} )  );
  }

  render() {
    return (
      <div>
        <p className="h1">My Collections</p>
        <a href="/items/new" className="btn btn-primary" style={{color: 'white'}}>New</a>
        <table className="table">
          <tbody>
          <tr>
            <th>Name</th>
            <th>Collected</th>
            <th style={{width: 80 + 'px'}}>Actions</th>
          </tr>
          {this.state.collections.map(function(item, key) {
               return (
                  <tr key = {key}>
                      <td>{item.Name}</td>
                      <td>{item.Collected} / {item.Total}</td>
                      <td style={{width: 80 + 'px'}}>
                        <a href={`collections/${item.CollectionId}/items`} className="btn btn-info">Info</a>
                      </td>
                  </tr>
                )
          })}
          </tbody>
        </table>
      </div>
    );
  }
}

export default CollectionIndex;

// angular-frontend/src/app/collections/collections.component.ts
import { Component, OnInit } from '@angular/core';
import { CollectionsService } from '../services/collections.service'
import { Observable } from 'rxjs';

@Component({
  selector: 'app-collections',
  templateUrl: './collections.component.html',
  styleUrls: ['./collections.component.scss']
})
export class CollectionsComponent implements OnInit {

  collections$: Object;
  
  constructor(private data: CollectionsService) { }

  ngOnInit() {
    this.data.getCollections().subscribe(
      data => this.collections$ = data 
    );
  }

}

<p class="h1">My Collections</p>

<div style="margin-bottom: 10px;">
<a href="./collections/new" class="btn btn-primary" style="color: white">New</a>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Collected</th>
        <th style="width:70px">Actions</th>
    </tr>
    
    <tr *ngFor="let collection of collections$">
      <td>{{collection.Name}}</td>
      <td>{{collection.Collected}} / {{collection.Total}}</td>
      <td><a href="./collection/{{collection.CollectionId}}/items" class="btn btn-info" style="color: white">Info</a></td>
    </tr>
</table>
